name: aws account connection

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to say hello to'
        required: true
        default: 'world'

jobs:
  printLog:
    runs-on: ubuntu-latest
    steps:
      - name: print log
        run: echo "Hello! ${{ github.event.inputs.name }}"